<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(WinMcpWindowsTfm)</TargetFramework>
    <AssemblyName>WinMcp.Server</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WinMcp.Core\WinMcp.Core.csproj" />
  </ItemGroup>

</Project>
