using System.Globalization;
using System.Text.RegularExpressions;

namespace WinMcp.Core.Symbols;

/// <summary>A <c>#define</c> from a Visual Studio <c>resource.h</c>.</summary>
public sealed record ResourceSymbol(string Name, int Value);

/// <summary>Parses <c>resource.h</c> files as generated by Visual Studio, tolerating hand edits.</summary>
public static partial class ResourceSymbolParser
{
    // #define IDC_EDIT_NAME   1001        (also hex, parenthesized, and trailing // or /* comments)
    [GeneratedRegex(@"^\s*#\s*define\s+(?<name>[A-Za-z_][A-Za-z0-9_]*)\s+\(?\s*(?<value>0[xX][0-9A-Fa-f]+|-?\d+)\s*\)?\s*(?://.*|/\*.*)?$")]
    private static partial Regex DefineLine();

    public static IReadOnlyList<ResourceSymbol> Parse(string text)
    {
        var symbols = new List<ResourceSymbol>();
        foreach (var line in text.Split('\n'))
        {
            var match = DefineLine().Match(line.TrimEnd('\r'));
            if (!match.Success)
                continue;
            var name = match.Groups["name"].Value;
            if (name.StartsWith("_APS_", StringComparison.Ordinal)) // Visual Studio's next-free-ID bookkeeping
                continue;
            var raw = match.Groups["value"].Value;
            var parsed = raw.StartsWith("0x", StringComparison.OrdinalIgnoreCase)
                ? int.TryParse(raw.AsSpan(2), NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture, out var hex) ? hex : (int?)null
                : int.TryParse(raw, NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out var dec) ? dec : null;
            if (parsed is { } value)
                symbols.Add(new ResourceSymbol(name, value));
        }
        return symbols;
    }
}
