namespace WinMcp.Core.Mfc;

/// <summary>
/// MFC's standard IDs from <c>afxres.h</c> (MSVC 14.44, generated): frame window IDs (<c>AFX_IDW_*</c>: toolbar,
/// status bar, view pane, dock bars) and framework commands (<c>ID_*</c>, e.g. <c>ID_APP_EXIT</c>). Every MFC
/// application uses them, so they are known without a <c>resource.h</c>. Range aliases (<c>*_FIRST</c>/<c>*_LAST</c>
/// other than the pane and record commands) are omitted; <c>AFX_IDC_*</c> (mostly cursors, and small numbers that
/// collide with application control IDs) is deliberately not included.
/// </summary>
public static class AfxIds
{
    /// <summary>IDs MFC gives the windows of a frame (<c>AFX_IDW_*</c>): used for window/control lookups.</summary>
    public static readonly IReadOnlyList<(string Name, int Id)> Windows =
    [
        ("AFX_IDW_TOOLBAR", 0xE800),
        ("AFX_IDW_STATUS_BAR", 0xE801),
        ("AFX_IDW_PREVIEW_BAR", 0xE802),
        ("AFX_IDW_RESIZE_BAR", 0xE803),
        ("AFX_IDW_REBAR", 0xE804),
        ("AFX_IDW_DIALOGBAR", 0xE805),
        ("AFX_IDW_MENUBAR", 0xE806),
        ("AFX_IDW_DOCKBAR_TOP", 0xE81B),
        ("AFX_IDW_DOCKBAR_LEFT", 0xE81C),
        ("AFX_IDW_DOCKBAR_RIGHT", 0xE81D),
        ("AFX_IDW_DOCKBAR_BOTTOM", 0xE81E),
        ("AFX_IDW_DOCKBAR_FLOAT", 0xE81F),
        ("AFX_IDW_PANE_FIRST", 0xE900),
        ("AFX_IDW_HSCROLL_FIRST", 0xEA00),
        ("AFX_IDW_VSCROLL_FIRST", 0xEA10),
        ("AFX_IDW_SIZE_BOX", 0xEA20),
    ];

    /// <summary>Framework command IDs (<c>ID_*</c>): menu items and toolbar buttons of MFC applications.</summary>
    public static readonly IReadOnlyList<(string Name, int Id)> Commands =
    [
        ("ID_INDICATOR_EXT", 0xE700),
        ("ID_INDICATOR_CAPS", 0xE701),
        ("ID_INDICATOR_NUM", 0xE702),
        ("ID_INDICATOR_SCRL", 0xE703),
        ("ID_INDICATOR_OVR", 0xE704),
        ("ID_INDICATOR_REC", 0xE705),
        ("ID_INDICATOR_KANA", 0xE706),
        ("ID_FILE_NEW", 0xE100),
        ("ID_FILE_OPEN", 0xE101),
        ("ID_FILE_CLOSE", 0xE102),
        ("ID_FILE_SAVE", 0xE103),
        ("ID_FILE_SAVE_AS", 0xE104),
        ("ID_FILE_PAGE_SETUP", 0xE105),
        ("ID_FILE_PRINT_SETUP", 0xE106),
        ("ID_FILE_PRINT", 0xE107),
        ("ID_FILE_PRINT_DIRECT", 0xE108),
        ("ID_FILE_PRINT_PREVIEW", 0xE109),
        ("ID_FILE_UPDATE", 0xE10A),
        ("ID_FILE_SAVE_COPY_AS", 0xE10B),
        ("ID_FILE_SEND_MAIL", 0xE10C),
        ("ID_FILE_NEW_FRAME", 0xE10D),
        ("ID_FILE_MRU_FILE1", 0xE110),
        ("ID_FILE_MRU_FILE2", 0xE111),
        ("ID_FILE_MRU_FILE3", 0xE112),
        ("ID_FILE_MRU_FILE4", 0xE113),
        ("ID_FILE_MRU_FILE5", 0xE114),
        ("ID_FILE_MRU_FILE6", 0xE115),
        ("ID_FILE_MRU_FILE7", 0xE116),
        ("ID_FILE_MRU_FILE8", 0xE117),
        ("ID_FILE_MRU_FILE9", 0xE118),
        ("ID_FILE_MRU_FILE10", 0xE119),
        ("ID_FILE_MRU_FILE11", 0xE11A),
        ("ID_FILE_MRU_FILE12", 0xE11B),
        ("ID_FILE_MRU_FILE13", 0xE11C),
        ("ID_FILE_MRU_FILE14", 0xE11D),
        ("ID_FILE_MRU_FILE15", 0xE11E),
        ("ID_FILE_MRU_FILE16", 0xE11F),
        ("ID_EDIT_CLEAR", 0xE120),
        ("ID_EDIT_CLEAR_ALL", 0xE121),
        ("ID_EDIT_COPY", 0xE122),
        ("ID_EDIT_CUT", 0xE123),
        ("ID_EDIT_FIND", 0xE124),
        ("ID_EDIT_PASTE", 0xE125),
        ("ID_EDIT_PASTE_LINK", 0xE126),
        ("ID_EDIT_PASTE_SPECIAL", 0xE127),
        ("ID_EDIT_REPEAT", 0xE128),
        ("ID_EDIT_REPLACE", 0xE129),
        ("ID_EDIT_SELECT_ALL", 0xE12A),
        ("ID_EDIT_UNDO", 0xE12B),
        ("ID_EDIT_REDO", 0xE12C),
        ("ID_WINDOW_NEW", 0xE130),
        ("ID_WINDOW_ARRANGE", 0xE131),
        ("ID_WINDOW_CASCADE", 0xE132),
        ("ID_WINDOW_TILE_HORZ", 0xE133),
        ("ID_WINDOW_TILE_VERT", 0xE134),
        ("ID_WINDOW_SPLIT", 0xE135),
        ("ID_APP_ABOUT", 0xE140),
        ("ID_APP_EXIT", 0xE141),
        ("ID_HELP_INDEX", 0xE142),
        ("ID_HELP_FINDER", 0xE143),
        ("ID_HELP_USING", 0xE144),
        ("ID_CONTEXT_HELP", 0xE145),
        ("ID_HELP", 0xE146),
        ("ID_DEFAULT_HELP", 0xE147),
        ("ID_NEXT_PANE", 0xE150),
        ("ID_PREV_PANE", 0xE151),
        ("ID_FORMAT_FONT", 0xE160),
        ("ID_OLE_INSERT_NEW", 0xE200),
        ("ID_OLE_EDIT_LINKS", 0xE201),
        ("ID_OLE_EDIT_CONVERT", 0xE202),
        ("ID_OLE_EDIT_CHANGE_ICON", 0xE203),
        ("ID_OLE_EDIT_PROPERTIES", 0xE204),
        ("ID_OLE_VERB_FIRST", 0xE210),
        ("ID_OLE_VERB_LAST", 0xE21F),
        ("ID_OLE_VERB_POPUP", 0xE220),
        ("ID_VIEW_TOOLBAR", 0xE800),
        ("ID_VIEW_STATUS_BAR", 0xE801),
        ("ID_VIEW_REBAR", 0xE804),
        ("ID_VIEW_AUTOARRANGE", 0xE805),
        ("ID_VIEW_SMALLICON", 0xE810),
        ("ID_VIEW_LARGEICON", 0xE811),
        ("ID_VIEW_LIST", 0xE812),
        ("ID_VIEW_DETAILS", 0xE813),
        ("ID_VIEW_LINEUP", 0xE814),
        ("ID_VIEW_BYNAME", 0xE815),
        ("ID_RECORD_FIRST", 0xE900),
        ("ID_RECORD_LAST", 0xE901),
        ("ID_RECORD_NEXT", 0xE902),
        ("ID_RECORD_PREV", 0xE903),
        ("ID_APPLY_NOW", 0x3021),
        ("ID_WIZBACK", 0x3023),
        ("ID_WIZNEXT", 0x3024),
        ("ID_WIZFINISH", 0x3025),
    ];
}
